package me.avocardo.guilds.utilities;

public enum AttributeType {

	ATTACK_MELEE,
	ATTACK_PROJECTILE,
	DEFENSE_MELEE,
	DEFENSE_PROJECTILE,
	DEFENSE_FALL,
	DEFENSE_SUFFOCATION,
	DEFENSE_CONTACT,
	DEFENSE_FIRE,
	DEFENSE_LAVA,
	DEFENSE_DROWNING,
	DEFENSE_EXPLOSION,
	DEFENSE_LIGHTNING,
	DEFENSE_STARVATION,
	DEFENSE_POISON,
	DEFENSE_MAGIC,
	DEFENSE_WITHER,
	XP_MULTIPLIER;
	
}
